"""chat conversation and event

Revision ID: 18c9104709b8
Revises: 4119562b5fd9
Create Date: 2026-08-04 12:20:36.770255

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18c9104709b8"
down_revision: str | Sequence[str] | None = "4119562b5fd9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("actor_kind", sa.String(), nullable=False),
        sa.Column("actor_agent_id", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=True),
        sa.Column("causation_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "actor_kind IN ('operator', 'orchestrator', 'agent', 'system')",
            name="ck_event_actor_kind",
        ),
        sa.CheckConstraint(
            "(actor_kind = 'agent' AND actor_agent_id IS NOT NULL AND "
            "actor_agent_id <> '') OR (actor_kind <> 'agent' AND "
            "actor_agent_id IS NULL)",
            name="ck_event_actor_agent_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "event_seq", name="uq_event_conversation_seq"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event")
    op.drop_table("conversation")
    # ### end Alembic commands ###
