"""create agent, session, outcome, settings and reasoning state

Revision ID: 380a27d7fddb
Revises: 9b6587dab793
Create Date: 2026-08-02 20:49:52.777034

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "380a27d7fddb"
down_revision: str | Sequence[str] | None = "9b6587dab793"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_outcome",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_table(
        "agent_session",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("backend", sa.String(), nullable=False),
        sa.Column("current_session_id", sa.String(), nullable=True),
        sa.Column("parent_agent_id", sa.String(), nullable=True),
        sa.Column("parent_session_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_table(
        "agent_session_history",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("agent_id", "seq"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("backend", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("goal", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("permission_mode", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reasoning_turn",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("reasoning", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("session_id", "seq"),
    )
    op.create_table(
        "settings_override",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings_override")
    op.drop_table("reasoning_turn")
    op.drop_table("agents")
    op.drop_table("agent_session_history")
    op.drop_table("agent_session")
    op.drop_table("agent_outcome")
    # ### end Alembic commands ###
