"""v0.2.0 baseline

Revision ID: 4119562b5fd9
Revises:
Create Date: 2026-08-04 04:24:56.366907

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4119562b5fd9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_outcome",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_table(
        "agent_session",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("backend", sa.String(), nullable=False),
        sa.Column("current_session_id", sa.String(), nullable=True),
        sa.Column("parent_agent_id", sa.String(), nullable=True),
        sa.Column("parent_session_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_table(
        "agent_session_history",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("agent_id", "seq"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("backend", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("goal", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("permission_mode", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auth_session",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("csrf", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("last_seen", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_change",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("resolved", sa.String(), nullable=False),
        sa.Column("attr", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("toplevel", sa.String(), nullable=False),
        sa.Column("action_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("log_tail", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("agent", sa.String(), nullable=False),
        sa.Column("requested_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seq"),
    )
    op.create_table(
        "digest",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("at", sa.Float(), nullable=False),
        sa.Column("schedule", sa.String(), nullable=False),
        sa.Column("verdict", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("delivery_error", sa.String(), nullable=False),
        sa.Column("states", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "host_action",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("proposal", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("decided_by", sa.String(), nullable=False),
        sa.Column("decided_at", sa.Float(), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seq"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cwd", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reasoning_turn",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("reasoning", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("session_id", "seq"),
    )
    op.create_table(
        "schedule",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("next_due", sa.Float(), nullable=False),
        sa.Column("last_run", sa.Float(), nullable=True),
        sa.Column("last_result", sa.String(), nullable=False),
        sa.Column("missed", sa.Integer(), nullable=False),
        sa.Column("runs", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "settings_override",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings_override")
    op.drop_table("schedule")
    op.drop_table("reasoning_turn")
    op.drop_table("projects")
    op.drop_table("host_action")
    op.drop_table("digest")
    op.drop_table("config_change")
    op.drop_table("auth_session")
    op.drop_table("agents")
    op.drop_table("agent_session_history")
    op.drop_table("agent_session")
    op.drop_table("agent_outcome")
    # ### end Alembic commands ###
