"""chat provider session

Revision ID: 4bc3435e4fdc
Revises: 53aaa107ce2d
Create Date: 2026-08-04 14:28:43.151457

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bc3435e4fdc"
down_revision: str | Sequence[str] | None = "53aaa107ce2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_session",
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("backend", sa.String(), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("provider_session_id", sa.String(), nullable=False),
        sa.Column("seeded_at", sa.Float(), nullable=False),
        sa.CheckConstraint("backend <> ''", name="ck_provider_session_backend"),
        sa.CheckConstraint(
            "provider_session_id <> ''", name="ck_provider_session_provider_session_id"
        ),
        sa.CheckConstraint(
            "policy_version >= 1", name="ck_provider_session_policy_version"
        ),
        sa.PrimaryKeyConstraint(
            "conversation_id", "backend", name="pk_provider_session"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provider_session")
    # ### end Alembic commands ###
