"""chat delivery

Revision ID: 53aaa107ce2d
Revises: 18c9104709b8
Create Date: 2026-08-04 13:38:05.639735

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53aaa107ce2d"
down_revision: str | Sequence[str] | None = "18c9104709b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery",
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("conversation_id", sa.String(), nullable=False),
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("claimed_at", sa.Float(), nullable=False),
        sa.Column("confirmed_at", sa.Float(), nullable=True),
        sa.CheckConstraint("channel <> ''", name="ck_delivery_channel"),
        sa.CheckConstraint(
            "(state = 'confirmed' AND confirmed_at IS NOT NULL) OR "
            "(state <> 'confirmed' AND confirmed_at IS NULL)",
            name="ck_delivery_confirmed_at",
        ),
        sa.CheckConstraint(
            "state IN ('claimed', 'confirmed')", name="ck_delivery_state"
        ),
        sa.PrimaryKeyConstraint(
            "channel", "conversation_id", "event_seq", name="pk_delivery"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivery")
    # ### end Alembic commands ###
