"""create legacy_import

Revision ID: 9b6587dab793
Revises: 8f8087f3cc9c
Create Date: 2026-08-02 18:53:56.462613

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b6587dab793"
down_revision: str | Sequence[str] | None = "8f8087f3cc9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_import",
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("imported_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("source"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("legacy_import")
    # ### end Alembic commands ###
