"""create config_change

Revision ID: e054a39a5fae
Revises: 3a5161b39846
Create Date: 2026-08-03 01:18:06.825233

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e054a39a5fae"
down_revision: str | Sequence[str] | None = "3a5161b39846"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_change",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("resolved", sa.String(), nullable=False),
        sa.Column("attr", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("toplevel", sa.String(), nullable=False),
        sa.Column("action_id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("log_tail", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("agent", sa.String(), nullable=False),
        sa.Column("requested_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("config_change")
    # ### end Alembic commands ###
